---
sf2_project_release: ~
sf2_project_php_path: php
sf2_project_keep_releases: 2
sf2_project_clean_versioning: true
sf2_project_console_opts: ''
sf2_project_composer_path: '/usr/local/bin'
sf2_project_composer_opts: '--optimize-autoloader --no-interaction'
sf2_fire_migrations: false
sf2_console_path: bin/console
sf2_logs_path: var/logs
